FROM ubuntu:18.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
            tigervnc-standalone-server \
            tigervnc-xorg-extension \
            tigervnc-viewer \
    && apt-get clean
