version: '3'

services:

  tigervnc-ubuntu:
    build:
      context: .
      args:
        FROM_IMAGE: ubuntu:18.04
    image: wshand/tigervnc:ubuntu

  tigervnc-debian:
    build:
      context: .
      args:
        FROM_IMAGE: debian:buster-slim
    image: wshand/tigervnc:debian
