version: '3'

services:

  lxde-vnc-debian:
    build:
      context: .
      args:
        FROM_IMAGE: wshand/novnc:debian
    image: wshand/lxqt-vnc:debian

  lxde-vnc-ubuntu:
    build:
      context: .
      args:
        FROM_IMAGE: wshand/novnc:ubuntu
    image: wshand/lxqt-vnc:ubuntu
