version: '3'

services:

  xfce-vnc-ubuntu:
    build:
      context: .
      args:
        FROM_IMAGE: wshand/novnc:ubuntu
    image: wshand/xfce-vnc:ubuntu

  xfce-vnc-debian:
    build:
      context: .
      args:
        FROM_IMAGE: wshand/novnc:debian
    image: wshand/xfce-vnc:debian
