FROM wshand/novnc:debian

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
            xfce4 \
            xfce4-goodies \
    && apt-get purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Configure VNC
ENV TERM=xterm-256color
COPY xstartup /etc/vnc/
