version: '2.3'

networks:
  cowrie_local:

services:

# Cowrie service
  cowrie:
    build: .
    container_name: cowrie
    restart: always
    tmpfs:
     - /tmp/cowrie:uid=2000,gid=2000
     - /tmp/cowrie/data:uid=2000,gid=2000
    networks:
     - cowrie_local
    ports:
     - "22:22"
     - "23:23"
    image: wshand/cowrie:latest
    read_only: true
    volumes:
     - cowrie:/persistent

volumes:
  cowrie:
