version: '3'

services:

  adbhoney:
    image: wshand/adbhoney:latest
    networks:
     - adbhoney_local
    ports:
     - "5555:5555"
    read_only: true
    volumes:
      - adbhoney:/persistent:rw
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 64M

  cowrie:
    image: wshand/cowrie:latest
    networks:
      - cowrie_local
    ports:
     - "22:22"
     - "23:23"
    tmpfs:
     - /tmp/cowrie:uid=2000,gid=2000
     - /tmp/cowrie/data:uid=2000,gid=2000
    read_only: true
    volumes:
     - cowrie:/persistent
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 64M

  dionaea:
    image: wshand/dionaea:latest
    networks:
      - dionaea_local
    stdin_open: true
    tty: true
    ports:
     - "20:20"
     - "21:21"
     - "42:42"
     - "69:69/udp"
     - "81:81"
     - "135:135"
     - "443:443"
     - "445:445"
     - "1433:1433"
     - "1723:1723"
     - "1883:1883"
     - "3306:3306"
     - "5060:5060"
     - "5060:5060/udp"
     - "5061:5061"
     - "27017:27017"
    image: "wshand/dionaea:latest"
    read_only: true
    volumes:
      - dionaea:/persistent:rw
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 32M

volumes:
  adbhoney:
  cowrie:
  dionaea:

networks:
  adbhoney_local:
  cowrie_local:
  dionaea_local:
