version: '3.4'

services:
  forensics:
    build:
      context: .
      args:
        FROM_IMAGE: wshand/xfce-vnc:debian
        GHIDRA_VERSION: 9.1_PUBLIC_20191023
        GHIDRA_SHA: 29d130dfe85da6ec45dfbf68a344506a8fdcc7cfe7f64a3e7ffb210052d1875e
    image: wshand/forensics
    volumes:
      - "forensics:/persistent"

volumes:
  forensics:
