version: '3.4'

services:
  forensics:
    build:
      context: .
    image: wshand/forensics
    environment:
      SCREEN_DIMS: "1200x800"
    volumes:
      - "forensics:/persistent"

volumes:
  forensics:
