version: '3'

services:

  novnc-debian:
    build:
      context: .
      args:
        FROM_IMAGE: debian:buster-slim
    image: wshand/novnc:debian

  novnc-ubuntu:
    build:
      context: .
      args:
        FROM_IMAGE: ubuntu:18.04
    image: wshand/novnc:ubuntu
